---
- project:
    templates:
      - publish-stx-docs
      - stx-api-ref-jobs
      - stx-release-notes-jobs
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
        - stx-distcloud-tox-py27
    gate:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
        - stx-distcloud-tox-py27

- job:
    name: stx-distcloud-tox-py27
    parent: tox
    description: Run py27 for distcloud
    required-projects:
      - starlingx/fault
      - starlingx/nfv
      - starlingx/update
      - starlingx/config
    vars:
      tox_envlist: py27
      tox_extra_args: -c tox.ini
